# Copy to group_vars/edge_group_3.yml
# reverse-ssh-links.yml uses these public paths for generated client links.

rssh_ws_path: /track_group3
rssh_push_path: /ping_group3

# main_reverse_ssh_port: 3234
